/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
    assertEquals("Sum of 2 and 3 is 5. Average is 2.5.", classUnderTest.getSumAndAverageOfAnd(2, 3));
    assertEquals("Sum of 1 to 10 is 55. Average is 5.5.", classUnderTest.getSumAndAverageOfTo(1, 10));
    assertEquals("Sum of odd of 1 to 10 is 25. Sum of even is 30.", classUnderTest.getSumOfOddAndEvenOfTo(1, 10));
  }
}
